trainer:
  tracking_metric: min
  num_epoch_repeats: 16
  num_epochs: 1000
  ray_batch_size: 1200
  nviews: [3, 4, 5]
  use_data_augmentation: true
  freeze_encoder: false

  loss:
    loss_type: logit
    rgb_loss_type: mse
    use_reprojection_loss: false
    reprojection_loss_weight: 0.2

  optimizer:
    learning_rate: 1.0e-4
    gamma: 0.99

